package te.app.nottaa.utils;

public class URLS {
    public final static String BASE_URL = "http://noqta-learn.com/api/";
    public final static String SPECIALIST = "teacher/get-specialists";
    public final static String ADD_GROUP = "teacher/create-group";
    public final static String HOME = "teacher/get-my-groups?search_key=";
    public final static String HOME_STUDENT = "student/get-groups?search_key=";
    public final static String INVITE_STUDENTS = "teacher/search-students?search_key=";
    public final static String SEND_INVITATIONS = "teacher/invite-students";
    public final static String ADD_TASK = "teacher/create-task";
    public final static String GROUP_DETAILS = "teacher/group-details?group_id=";
    public final static String DELETE_GROUP = "teacher/remove-group";
    public final static String LOGIN_SOCIAL = "v1/social_register";
    public final static String LOGIN_PASSWORD = "user/login";
    public final static String REGISTER = "user/register";
    public final static String DELETE_TASK = "teacher/remove-task";
    public final static String POINTS = "teacher/get-my-gifts?page=";
    public final static String BOARD = "app/app-explanation";
    public final static String CONFIRM_CODE = "user/otp-check";
    public final static String UPDATE_PROFILE = "user/update-profile";
    public static final String FORGET_PASSWORD = "user/verify-email";
    public static final String CHANGE_PASSWORD = "user/change-password";
    public final static String ADD_GIFT = "teacher/create-gift";
    public final static String DELETE_GIFT = "teacher/remove-gift";
    public final static String GROUP_STUDENTS = "teacher/get-group-students?group_id=";
    public final static String GROUP_STUDENTS_REQUESTS = "teacher/get-my-requests?group_id=";
    public final static String SEND_JOIN_REQUEST = "student/join-group";
    public final static String CHANGE_STUDENT_REQUEST_STATUS = "teacher/request-change-status";
    public final static String TASK_DETAILS = "teacher/get-task-details?student_id=";
    public final static String ADD_ANSWER = "student/answer-task";
    public final static String STUDENT_TASKS = "student/get-my-tasks?page=";
    public final static String STUDENT_POINTS = "student/get-gifts?page=";
    public static final String MOVE_POINTS = "student/move-points-to-store";
    public final static String LEAVE_GROUP = "student/leave-group";
    public final static String GET_GIFT = "student/exchange-gift";
    public static final String CONTACT_US = " app/complains-suggestions";
    public static final String GROUP_STUDENT_TASKS = "teacher/get-student-tasks?student_id=";
    public final static String GIVE_POINTS = "teacher/give-points";
    public final static String NOTIFICATIONS = "app/get-notifications";
    public static final String TAKE_CHANCE = "student/take-chance";
    public static final String PRIVACY = "v1/privacy_policy";
    public static final String REPORT_REASONS = "v1/report_reasons";
    public static final String CHANGE_PROFILE_PASSWORD = "v1/provider/profile/password";
    public static final String BAN_USER = "v1/profile/ban";
    public static final String ABOUT = "app/about-us";
    public static final String TERMS = "app/terms-conditions";
    public final static String REPORT_USER = "v1/profile/report";
    public final static String SEE_FIRST = "v1/follow/see_first";

}
